#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Write the puzzle input for the given day to the ./i/XX file.
# The filename will gain a leading zero if it is a single digit.
#
# Usage:   ./get <day>
# Example: ./get 1 => causes "./i/01" to be written
#
# Note that on the adventofcode.com site, single-digit days do not have a
# leading zero.

url="https://adventofcode.com/2022/day/${1}/input"
key=`cat session.key`
out=$(printf "./i/%02d" ${1})

curl -o ${out} --cookie "session=${key}" ${url}
